config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :tickets
  end
  resources :users

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets, dependent: :destroy
  validates_presence_of :category, :name, :date_and_time, :capacity
  validates_numericality_of :capacity, :greater_than => 0

  def format_date
    self.date_and_time.strftime("%b %d, %Y")
  end

  def format_time
    self.date_and_time.strftime("%l:%M%P")
  end

  def tickets_remaining
    self.capacity - self.tickets.count
  end

  def sold_out?
    self.tickets_remaining == 0
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :events, through: :tickets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = 'This event has been added.'
      redirect_to event_path(@event)
    else
      @errors = @event.errors.full_messages
      render new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = 'This event has been updated.'
      redirect_to event_path(@event)
    else
      @errors = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end


  private

  def event_params
    params.require(:event).permit(:category, :name, :date_and_time, :capacity)
  end

  # def set_event
  #   @event = Event.find(params[:id])
  # end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:notice] = 'Ticket sucessfully purchased'
      redirect_to user_path(current_user)
    else
      @errors = @ticket.errors.full_messages
      render new_event_ticket_path
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:event_id, :price, :seat, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Update event:</h1>

<% if @errors %>
  <% @errors.each do |msg| %>
    <ul>
      <li class="error"><%= msg %></li>
    </ul>
  <% end %>
<% end %>

<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.datetime_select :date_and_time, :ampm => true, :minute_step => 15 %><br>
  </p>
  <p>
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </p>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<div class="container">
  <div class="row"  id="main-header">
    <div class="col-md-12">
      <h1>Upcoming Events</h1>
    </div>
  </div>
</div>
<% if current_user.try(:admin) %>
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12" id="admin-option">
          <p>Admin Panel</p>
          <%= link_to 'Add New Event', new_event_path %>
      </div>
    </div>
</div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row text-center" id="event-listing">
        <div class="col-md-2 text-bold">
          <p id="column-header">Event Category</p>
        </div>
        <div class="col-md-4">
          <p id="column-header">Event Name</p>
        </div>
        <div class="col-md-2">
          <p id="column-header">Date</p>
        </div>
        <div class="col-md-2">
          <p id="column-header">Time</p>
        </div>
        <div class="col-md-2">
          <p id="column-header">Tickets Remaining</p>
        </div>
      </div>
      <% @events.each do |event| %>
        <div class="row text-center" id="event-listing">
          <div class="col-md-2">
            <%= event.category %>
          </div>
          <div class="col-md-4">
            <%= link_to event.name, event_path(event) %>
          </div>
          <div class="col-md-2">
            <%= event.format_date %>
          </div>
          <div class="col-md-2">
            <%= event.format_time %>
          </div>
          <div class="col-md-2">
            <%= event.tickets_remaining %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<% if @errors %>
  <% @errors.each do |msg| %>
    <ul>
      <li class="error"><%= msg %></li>
    </ul>
  <% end %>
<% end %>

<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.datetime_select :date_and_time, :ampm => true, :minute_step => 15 %><br>
  </p>
  <p>
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </p>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<div class="container">
  <div class="row" id="main-header">
    <h1><%= @event.name %></h1>
  </div>
</div>

<p class="notice"><%= notice %></p>

<% if current_user.try(:admin?) %>
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12" id="admin-option">
        <p>Admin Panel</p>
        <%= link_to "Edit", edit_event_path(@event) %> |
        <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure you would like to delete this event?"} %>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12" id="single-event">
      <p>Tickets Remaining: <%= @event.tickets_remaining %> </p>
      <p>Date: <%= @event.format_date %></p>
      <p>Time: <%= @event.format_time %></p>
      <% if @event.sold_out? %>
        <%= "Sorry, this event is sold out" %>
      <% else %>
        <% if !current_user %>
          <%= "You must be logged in to buy tickets" %>
        <% else %>
          <%= link_to "Buy tickets here.", new_event_ticket_path(@event) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DenverTheater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag *webpack_asset_paths("application") %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body class="app">
    <%= render "pages/notice" %>

    <section>
      <div class="nav">
        <div class="container">
          <ul class="pull-left">
            <% if current_user %>
              <li><%= link_to "#{current_user.email} Dashboard", user_path(current_user) %></li> |
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>  |
              <li><%= link_to "Register", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </section>
    <div class="nav">
        <div class="container">
          <ul class="pull-left">
            <li><%= link_to "Home", root_path %></li> |
            <li><%= link_to "All Events", events_path %></li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/_notice.html.erb
<div class="container">
  <% if notice.present? %>
    <aside class="alert alert-info">
      <%= notice %>
    </aside>
  <% end %>
  <% if alert.present? %>
    <aside class="alert alert-danger">
      <%= alert %>
    </aside>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row text-center" id="main-header">
    <div class="col-md-12">
      <h1>Featured Events </h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="item active">
            <img src="https://goo.gl/LCbTHR" alt="Hockey">
            <div class="carousel-caption">
              <h3>2017 Hockey Playoffs</h3>
              <p>Check out the latest action on the ice!</p>
            </div>
          </div>
          <div class="item">
            <img src="https://goo.gl/lrfvig" alt="Concert">
            <div class="carousel-caption">
              <h3>Summer concert series announced</h3>
              <p>Come take a look at who's coming this summer!</p>
            </div>
          </div>
          <div class="item">
            <img src="https://goo.gl/a4bxrx" alt="Craft Beer Festival">
            <div class="carousel-caption">
              <h3>Craft Beer Festival</h3>
              <p>Enjoy a day of cold brews and good music!</p>
            </div>
          </div>
        </div>

        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>


<!-- Placeholder for future filtered event lists -->
<!-- <div class="main-content">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <p>"Heyyooooo"</p>
      </div>
      <div class="col-md-4">
        <p>Boooyyaaahhhh</p>
      </div>
      <div class="col-md-4">
        <p>Ayyoooo</p>
      </div>
    </div>
  </div>
</div> -->

app/views/tickets/new.html.erb
<div class="container">
  <h1>Buy ticket for <%= @event.name %> </h1>
</div>

<div class="container" id="buy-ticket">
  <%= form_for ([@event, @ticket]) do |f| %>
  <%= f.hidden_field :event_id, :value => @event.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <p>
    <%= f.label :price %>
    <%= f.select :price, [['VIP $100', 100],['GA $50', 50]] %>
  </p>
  <p>
    <%= f.label :seat %>
    <%= f.select :seat, ['GA'] %>
  </p>
  <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <h1>Dashboard for: <%= current_user.email %></h1>
</div>

<div class="container">
    <h2>Events attending:</h2>

    <ul>
    <% @user.events.group("id").each do |event| %>
      <li><%= event.name %></li>
    <% end %>
    </ul>

</div>